import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

interface StaticAsset {
  contentType: string;
  base64: string;
}

const distPath = path.resolve("dist");
const outputPath = path.resolve("src/cli/assets.generated.ts");

const mimeTypes: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon"
};

const assets: Record<string, StaticAsset> = {};

await collect(distPath);

const source = `// This file is generated by scripts/generate-static-assets.ts.
// Run \`bun run generate:assets\` after rebuilding the UI.

export interface StaticAsset {
  contentType: string;
  base64: string;
}

export const STATIC_ASSETS: Record<string, StaticAsset> = ${JSON.stringify(assets, null, 2)};
`;

await writeFile(outputPath, source);

async function collect(directory: string): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const absolutePath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      await collect(absolutePath);
      continue;
    }

    if (!entry.isFile()) continue;

    const routePath = `/${path.relative(distPath, absolutePath).split(path.sep).join("/")}`;
    const buffer = await readFile(absolutePath);
    assets[routePath] = {
      contentType: mimeTypes[path.extname(absolutePath)] ?? "application/octet-stream",
      base64: buffer.toString("base64")
    };
  }
}
